//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 2.0.5.0
// 
namespace s_remote.remote {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://www.cs.rit.edu/~ats/db", ItemName="string")]
    public class ArrayOfString : System.Collections.ObjectModel.ObservableCollection<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.cs.rit.edu/~ats/db", ConfigurationName="remote.ServiceSoap")]
    public interface ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://www.cs.rit.edu/~ats/db/get_Count", ReplyAction="*")]
        System.IAsyncResult Beginget_Count(System.AsyncCallback callback, object asyncState);
        
        int Endget_Count(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://www.cs.rit.edu/~ats/db/Search", ReplyAction="*")]
        System.IAsyncResult BeginSearch(s_remote.remote.SearchRequest request, System.AsyncCallback callback, object asyncState);
        
        s_remote.remote.SearchResponse EndSearch(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://www.cs.rit.edu/~ats/db/Enter", ReplyAction="*")]
        System.IAsyncResult BeginEnter(s_remote.remote.EnterRequest request, System.AsyncCallback callback, object asyncState);
        
        s_remote.remote.EnterResponse EndEnter(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://www.cs.rit.edu/~ats/db/Remove", ReplyAction="*")]
        System.IAsyncResult BeginRemove(s_remote.remote.RemoveRequest request, System.AsyncCallback callback, object asyncState);
        
        s_remote.remote.RemoveResponse EndRemove(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Search", Namespace="http://www.cs.rit.edu/~ats/db", Order=0)]
        public s_remote.remote.SearchRequestBody Body;
        
        public SearchRequest() {
        }
        
        public SearchRequest(s_remote.remote.SearchRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.cs.rit.edu/~ats/db")]
    public partial class SearchRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public s_remote.remote.ArrayOfString keys;
        
        public SearchRequestBody() {
        }
        
        public SearchRequestBody(s_remote.remote.ArrayOfString keys) {
            this.keys = keys;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchResponse", Namespace="http://www.cs.rit.edu/~ats/db", Order=0)]
        public s_remote.remote.SearchResponseBody Body;
        
        public SearchResponse() {
        }
        
        public SearchResponse(s_remote.remote.SearchResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.cs.rit.edu/~ats/db")]
    public partial class SearchResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.ObjectModel.ObservableCollection<s_remote.remote.ArrayOfString> SearchResult;
        
        public SearchResponseBody() {
        }
        
        public SearchResponseBody(System.Collections.ObjectModel.ObservableCollection<s_remote.remote.ArrayOfString> SearchResult) {
            this.SearchResult = SearchResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Enter", Namespace="http://www.cs.rit.edu/~ats/db", Order=0)]
        public s_remote.remote.EnterRequestBody Body;
        
        public EnterRequest() {
        }
        
        public EnterRequest(s_remote.remote.EnterRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.cs.rit.edu/~ats/db")]
    public partial class EnterRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public s_remote.remote.ArrayOfString tuple;
        
        public EnterRequestBody() {
        }
        
        public EnterRequestBody(s_remote.remote.ArrayOfString tuple) {
            this.tuple = tuple;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnterResponse", Namespace="http://www.cs.rit.edu/~ats/db", Order=0)]
        public s_remote.remote.EnterResponseBody Body;
        
        public EnterResponse() {
        }
        
        public EnterResponse(s_remote.remote.EnterResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.cs.rit.edu/~ats/db")]
    public partial class EnterResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool EnterResult;
        
        public EnterResponseBody() {
        }
        
        public EnterResponseBody(bool EnterResult) {
            this.EnterResult = EnterResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Remove", Namespace="http://www.cs.rit.edu/~ats/db", Order=0)]
        public s_remote.remote.RemoveRequestBody Body;
        
        public RemoveRequest() {
        }
        
        public RemoveRequest(s_remote.remote.RemoveRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.cs.rit.edu/~ats/db")]
    public partial class RemoveRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public s_remote.remote.ArrayOfString keys;
        
        public RemoveRequestBody() {
        }
        
        public RemoveRequestBody(s_remote.remote.ArrayOfString keys) {
            this.keys = keys;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemoveResponse", Namespace="http://www.cs.rit.edu/~ats/db", Order=0)]
        public s_remote.remote.RemoveResponseBody Body;
        
        public RemoveResponse() {
        }
        
        public RemoveResponse(s_remote.remote.RemoveResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.cs.rit.edu/~ats/db")]
    public partial class RemoveResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool RemoveResult;
        
        public RemoveResponseBody() {
        }
        
        public RemoveResponseBody(bool RemoveResult) {
            this.RemoveResult = RemoveResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ServiceSoapChannel : s_remote.remote.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class get_CountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public get_CountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class SearchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SearchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<s_remote.remote.ArrayOfString> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<s_remote.remote.ArrayOfString>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class EnterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public EnterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class RemoveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public RemoveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<s_remote.remote.ServiceSoap>, s_remote.remote.ServiceSoap {
        
        private BeginOperationDelegate onBeginget_CountDelegate;
        
        private EndOperationDelegate onEndget_CountDelegate;
        
        private System.Threading.SendOrPostCallback onget_CountCompletedDelegate;
        
        private BeginOperationDelegate onBeginSearchDelegate;
        
        private EndOperationDelegate onEndSearchDelegate;
        
        private System.Threading.SendOrPostCallback onSearchCompletedDelegate;
        
        private BeginOperationDelegate onBeginEnterDelegate;
        
        private EndOperationDelegate onEndEnterDelegate;
        
        private System.Threading.SendOrPostCallback onEnterCompletedDelegate;
        
        private BeginOperationDelegate onBeginRemoveDelegate;
        
        private EndOperationDelegate onEndRemoveDelegate;
        
        private System.Threading.SendOrPostCallback onRemoveCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<get_CountCompletedEventArgs> get_CountCompleted;
        
        public event System.EventHandler<SearchCompletedEventArgs> SearchCompleted;
        
        public event System.EventHandler<EnterCompletedEventArgs> EnterCompleted;
        
        public event System.EventHandler<RemoveCompletedEventArgs> RemoveCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult s_remote.remote.ServiceSoap.Beginget_Count(System.AsyncCallback callback, object asyncState) {
            return base.Channel.Beginget_Count(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        int s_remote.remote.ServiceSoap.Endget_Count(System.IAsyncResult result) {
            return base.Channel.Endget_Count(result);
        }
        
        private System.IAsyncResult OnBeginget_Count(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((s_remote.remote.ServiceSoap)(this)).Beginget_Count(callback, asyncState);
        }
        
        private object[] OnEndget_Count(System.IAsyncResult result) {
            int retVal = ((s_remote.remote.ServiceSoap)(this)).Endget_Count(result);
            return new object[] {
                    retVal};
        }
        
        private void Onget_CountCompleted(object state) {
            if ((this.get_CountCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.get_CountCompleted(this, new get_CountCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void get_CountAsync() {
            this.get_CountAsync(null);
        }
        
        public void get_CountAsync(object userState) {
            if ((this.onBeginget_CountDelegate == null)) {
                this.onBeginget_CountDelegate = new BeginOperationDelegate(this.OnBeginget_Count);
            }
            if ((this.onEndget_CountDelegate == null)) {
                this.onEndget_CountDelegate = new EndOperationDelegate(this.OnEndget_Count);
            }
            if ((this.onget_CountCompletedDelegate == null)) {
                this.onget_CountCompletedDelegate = new System.Threading.SendOrPostCallback(this.Onget_CountCompleted);
            }
            base.InvokeAsync(this.onBeginget_CountDelegate, null, this.onEndget_CountDelegate, this.onget_CountCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult s_remote.remote.ServiceSoap.BeginSearch(s_remote.remote.SearchRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSearch(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginSearch(s_remote.remote.ArrayOfString keys, System.AsyncCallback callback, object asyncState) {
            s_remote.remote.SearchRequest inValue = new s_remote.remote.SearchRequest();
            inValue.Body = new s_remote.remote.SearchRequestBody();
            inValue.Body.keys = keys;
            return ((s_remote.remote.ServiceSoap)(this)).BeginSearch(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        s_remote.remote.SearchResponse s_remote.remote.ServiceSoap.EndSearch(System.IAsyncResult result) {
            return base.Channel.EndSearch(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.Collections.ObjectModel.ObservableCollection<s_remote.remote.ArrayOfString> EndSearch(System.IAsyncResult result) {
            s_remote.remote.SearchResponse retVal = ((s_remote.remote.ServiceSoap)(this)).EndSearch(result);
            return retVal.Body.SearchResult;
        }
        
        private System.IAsyncResult OnBeginSearch(object[] inValues, System.AsyncCallback callback, object asyncState) {
            s_remote.remote.ArrayOfString keys = ((s_remote.remote.ArrayOfString)(inValues[0]));
            return this.BeginSearch(keys, callback, asyncState);
        }
        
        private object[] OnEndSearch(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<s_remote.remote.ArrayOfString> retVal = this.EndSearch(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSearchCompleted(object state) {
            if ((this.SearchCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SearchCompleted(this, new SearchCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SearchAsync(s_remote.remote.ArrayOfString keys) {
            this.SearchAsync(keys, null);
        }
        
        public void SearchAsync(s_remote.remote.ArrayOfString keys, object userState) {
            if ((this.onBeginSearchDelegate == null)) {
                this.onBeginSearchDelegate = new BeginOperationDelegate(this.OnBeginSearch);
            }
            if ((this.onEndSearchDelegate == null)) {
                this.onEndSearchDelegate = new EndOperationDelegate(this.OnEndSearch);
            }
            if ((this.onSearchCompletedDelegate == null)) {
                this.onSearchCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSearchCompleted);
            }
            base.InvokeAsync(this.onBeginSearchDelegate, new object[] {
                        keys}, this.onEndSearchDelegate, this.onSearchCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult s_remote.remote.ServiceSoap.BeginEnter(s_remote.remote.EnterRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginEnter(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginEnter(s_remote.remote.ArrayOfString tuple, System.AsyncCallback callback, object asyncState) {
            s_remote.remote.EnterRequest inValue = new s_remote.remote.EnterRequest();
            inValue.Body = new s_remote.remote.EnterRequestBody();
            inValue.Body.tuple = tuple;
            return ((s_remote.remote.ServiceSoap)(this)).BeginEnter(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        s_remote.remote.EnterResponse s_remote.remote.ServiceSoap.EndEnter(System.IAsyncResult result) {
            return base.Channel.EndEnter(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool EndEnter(System.IAsyncResult result) {
            s_remote.remote.EnterResponse retVal = ((s_remote.remote.ServiceSoap)(this)).EndEnter(result);
            return retVal.Body.EnterResult;
        }
        
        private System.IAsyncResult OnBeginEnter(object[] inValues, System.AsyncCallback callback, object asyncState) {
            s_remote.remote.ArrayOfString tuple = ((s_remote.remote.ArrayOfString)(inValues[0]));
            return this.BeginEnter(tuple, callback, asyncState);
        }
        
        private object[] OnEndEnter(System.IAsyncResult result) {
            bool retVal = this.EndEnter(result);
            return new object[] {
                    retVal};
        }
        
        private void OnEnterCompleted(object state) {
            if ((this.EnterCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.EnterCompleted(this, new EnterCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void EnterAsync(s_remote.remote.ArrayOfString tuple) {
            this.EnterAsync(tuple, null);
        }
        
        public void EnterAsync(s_remote.remote.ArrayOfString tuple, object userState) {
            if ((this.onBeginEnterDelegate == null)) {
                this.onBeginEnterDelegate = new BeginOperationDelegate(this.OnBeginEnter);
            }
            if ((this.onEndEnterDelegate == null)) {
                this.onEndEnterDelegate = new EndOperationDelegate(this.OnEndEnter);
            }
            if ((this.onEnterCompletedDelegate == null)) {
                this.onEnterCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnEnterCompleted);
            }
            base.InvokeAsync(this.onBeginEnterDelegate, new object[] {
                        tuple}, this.onEndEnterDelegate, this.onEnterCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult s_remote.remote.ServiceSoap.BeginRemove(s_remote.remote.RemoveRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRemove(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginRemove(s_remote.remote.ArrayOfString keys, System.AsyncCallback callback, object asyncState) {
            s_remote.remote.RemoveRequest inValue = new s_remote.remote.RemoveRequest();
            inValue.Body = new s_remote.remote.RemoveRequestBody();
            inValue.Body.keys = keys;
            return ((s_remote.remote.ServiceSoap)(this)).BeginRemove(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        s_remote.remote.RemoveResponse s_remote.remote.ServiceSoap.EndRemove(System.IAsyncResult result) {
            return base.Channel.EndRemove(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool EndRemove(System.IAsyncResult result) {
            s_remote.remote.RemoveResponse retVal = ((s_remote.remote.ServiceSoap)(this)).EndRemove(result);
            return retVal.Body.RemoveResult;
        }
        
        private System.IAsyncResult OnBeginRemove(object[] inValues, System.AsyncCallback callback, object asyncState) {
            s_remote.remote.ArrayOfString keys = ((s_remote.remote.ArrayOfString)(inValues[0]));
            return this.BeginRemove(keys, callback, asyncState);
        }
        
        private object[] OnEndRemove(System.IAsyncResult result) {
            bool retVal = this.EndRemove(result);
            return new object[] {
                    retVal};
        }
        
        private void OnRemoveCompleted(object state) {
            if ((this.RemoveCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RemoveCompleted(this, new RemoveCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RemoveAsync(s_remote.remote.ArrayOfString keys) {
            this.RemoveAsync(keys, null);
        }
        
        public void RemoveAsync(s_remote.remote.ArrayOfString keys, object userState) {
            if ((this.onBeginRemoveDelegate == null)) {
                this.onBeginRemoveDelegate = new BeginOperationDelegate(this.OnBeginRemove);
            }
            if ((this.onEndRemoveDelegate == null)) {
                this.onEndRemoveDelegate = new EndOperationDelegate(this.OnEndRemove);
            }
            if ((this.onRemoveCompletedDelegate == null)) {
                this.onRemoveCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRemoveCompleted);
            }
            base.InvokeAsync(this.onBeginRemoveDelegate, new object[] {
                        keys}, this.onEndRemoveDelegate, this.onRemoveCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override s_remote.remote.ServiceSoap CreateChannel() {
            return new ServiceSoapClientChannel(this);
        }
        
        private class ServiceSoapClientChannel : ChannelBase<s_remote.remote.ServiceSoap>, s_remote.remote.ServiceSoap {
            
            public ServiceSoapClientChannel(System.ServiceModel.ClientBase<s_remote.remote.ServiceSoap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult Beginget_Count(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("get_Count", _args, callback, asyncState);
                return _result;
            }
            
            public int Endget_Count(System.IAsyncResult result) {
                object[] _args = new object[0];
                int _result = ((int)(base.EndInvoke("get_Count", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginSearch(s_remote.remote.SearchRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("Search", _args, callback, asyncState);
                return _result;
            }
            
            public s_remote.remote.SearchResponse EndSearch(System.IAsyncResult result) {
                object[] _args = new object[0];
                s_remote.remote.SearchResponse _result = ((s_remote.remote.SearchResponse)(base.EndInvoke("Search", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginEnter(s_remote.remote.EnterRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("Enter", _args, callback, asyncState);
                return _result;
            }
            
            public s_remote.remote.EnterResponse EndEnter(System.IAsyncResult result) {
                object[] _args = new object[0];
                s_remote.remote.EnterResponse _result = ((s_remote.remote.EnterResponse)(base.EndInvoke("Enter", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginRemove(s_remote.remote.RemoveRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("Remove", _args, callback, asyncState);
                return _result;
            }
            
            public s_remote.remote.RemoveResponse EndRemove(System.IAsyncResult result) {
                object[] _args = new object[0];
                s_remote.remote.RemoveResponse _result = ((s_remote.remote.RemoveResponse)(base.EndInvoke("Remove", _args, result)));
                return _result;
            }
        }
    }
}
