//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Axel.Database.remote {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://www.cs.rit.edu/~ats/db", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.cs.rit.edu/~ats/db", ConfigurationName="remote.ServiceSoap")]
    public interface ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cs.rit.edu/~ats/db/get_Count", ReplyAction="*")]
        int get_Count();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://www.cs.rit.edu/~ats/db/get_Count", ReplyAction="*")]
        System.IAsyncResult Beginget_Count(System.AsyncCallback callback, object asyncState);
        
        int Endget_Count(System.IAsyncResult result);
        
        // CODEGEN: Generating message contract since element name keys from namespace http://www.cs.rit.edu/~ats/db is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cs.rit.edu/~ats/db/Search", ReplyAction="*")]
        Axel.Database.remote.SearchResponse Search(Axel.Database.remote.SearchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://www.cs.rit.edu/~ats/db/Search", ReplyAction="*")]
        System.IAsyncResult BeginSearch(Axel.Database.remote.SearchRequest request, System.AsyncCallback callback, object asyncState);
        
        Axel.Database.remote.SearchResponse EndSearch(System.IAsyncResult result);
        
        // CODEGEN: Generating message contract since element name tuple from namespace http://www.cs.rit.edu/~ats/db is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cs.rit.edu/~ats/db/Enter", ReplyAction="*")]
        Axel.Database.remote.EnterResponse Enter(Axel.Database.remote.EnterRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://www.cs.rit.edu/~ats/db/Enter", ReplyAction="*")]
        System.IAsyncResult BeginEnter(Axel.Database.remote.EnterRequest request, System.AsyncCallback callback, object asyncState);
        
        Axel.Database.remote.EnterResponse EndEnter(System.IAsyncResult result);
        
        // CODEGEN: Generating message contract since element name keys from namespace http://www.cs.rit.edu/~ats/db is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cs.rit.edu/~ats/db/Remove", ReplyAction="*")]
        Axel.Database.remote.RemoveResponse Remove(Axel.Database.remote.RemoveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://www.cs.rit.edu/~ats/db/Remove", ReplyAction="*")]
        System.IAsyncResult BeginRemove(Axel.Database.remote.RemoveRequest request, System.AsyncCallback callback, object asyncState);
        
        Axel.Database.remote.RemoveResponse EndRemove(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Search", Namespace="http://www.cs.rit.edu/~ats/db", Order=0)]
        public Axel.Database.remote.SearchRequestBody Body;
        
        public SearchRequest() {
        }
        
        public SearchRequest(Axel.Database.remote.SearchRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.cs.rit.edu/~ats/db")]
    public partial class SearchRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Axel.Database.remote.ArrayOfString keys;
        
        public SearchRequestBody() {
        }
        
        public SearchRequestBody(Axel.Database.remote.ArrayOfString keys) {
            this.keys = keys;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchResponse", Namespace="http://www.cs.rit.edu/~ats/db", Order=0)]
        public Axel.Database.remote.SearchResponseBody Body;
        
        public SearchResponse() {
        }
        
        public SearchResponse(Axel.Database.remote.SearchResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.cs.rit.edu/~ats/db")]
    public partial class SearchResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Axel.Database.remote.ArrayOfString[] SearchResult;
        
        public SearchResponseBody() {
        }
        
        public SearchResponseBody(Axel.Database.remote.ArrayOfString[] SearchResult) {
            this.SearchResult = SearchResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Enter", Namespace="http://www.cs.rit.edu/~ats/db", Order=0)]
        public Axel.Database.remote.EnterRequestBody Body;
        
        public EnterRequest() {
        }
        
        public EnterRequest(Axel.Database.remote.EnterRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.cs.rit.edu/~ats/db")]
    public partial class EnterRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Axel.Database.remote.ArrayOfString tuple;
        
        public EnterRequestBody() {
        }
        
        public EnterRequestBody(Axel.Database.remote.ArrayOfString tuple) {
            this.tuple = tuple;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnterResponse", Namespace="http://www.cs.rit.edu/~ats/db", Order=0)]
        public Axel.Database.remote.EnterResponseBody Body;
        
        public EnterResponse() {
        }
        
        public EnterResponse(Axel.Database.remote.EnterResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.cs.rit.edu/~ats/db")]
    public partial class EnterResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool EnterResult;
        
        public EnterResponseBody() {
        }
        
        public EnterResponseBody(bool EnterResult) {
            this.EnterResult = EnterResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Remove", Namespace="http://www.cs.rit.edu/~ats/db", Order=0)]
        public Axel.Database.remote.RemoveRequestBody Body;
        
        public RemoveRequest() {
        }
        
        public RemoveRequest(Axel.Database.remote.RemoveRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.cs.rit.edu/~ats/db")]
    public partial class RemoveRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Axel.Database.remote.ArrayOfString keys;
        
        public RemoveRequestBody() {
        }
        
        public RemoveRequestBody(Axel.Database.remote.ArrayOfString keys) {
            this.keys = keys;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemoveResponse", Namespace="http://www.cs.rit.edu/~ats/db", Order=0)]
        public Axel.Database.remote.RemoveResponseBody Body;
        
        public RemoveResponse() {
        }
        
        public RemoveResponse(Axel.Database.remote.RemoveResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.cs.rit.edu/~ats/db")]
    public partial class RemoveResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool RemoveResult;
        
        public RemoveResponseBody() {
        }
        
        public RemoveResponseBody(bool RemoveResult) {
            this.RemoveResult = RemoveResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ServiceSoapChannel : Axel.Database.remote.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class get_CountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public get_CountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class SearchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SearchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Axel.Database.remote.ArrayOfString[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Axel.Database.remote.ArrayOfString[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class EnterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public EnterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class RemoveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public RemoveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<Axel.Database.remote.ServiceSoap>, Axel.Database.remote.ServiceSoap {
        
        private BeginOperationDelegate onBeginget_CountDelegate;
        
        private EndOperationDelegate onEndget_CountDelegate;
        
        private System.Threading.SendOrPostCallback onget_CountCompletedDelegate;
        
        private BeginOperationDelegate onBeginSearchDelegate;
        
        private EndOperationDelegate onEndSearchDelegate;
        
        private System.Threading.SendOrPostCallback onSearchCompletedDelegate;
        
        private BeginOperationDelegate onBeginEnterDelegate;
        
        private EndOperationDelegate onEndEnterDelegate;
        
        private System.Threading.SendOrPostCallback onEnterCompletedDelegate;
        
        private BeginOperationDelegate onBeginRemoveDelegate;
        
        private EndOperationDelegate onEndRemoveDelegate;
        
        private System.Threading.SendOrPostCallback onRemoveCompletedDelegate;
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<get_CountCompletedEventArgs> get_CountCompleted;
        
        public event System.EventHandler<SearchCompletedEventArgs> SearchCompleted;
        
        public event System.EventHandler<EnterCompletedEventArgs> EnterCompleted;
        
        public event System.EventHandler<RemoveCompletedEventArgs> RemoveCompleted;
        
        public int get_Count() {
            return base.Channel.get_Count();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult Beginget_Count(System.AsyncCallback callback, object asyncState) {
            return base.Channel.Beginget_Count(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public int Endget_Count(System.IAsyncResult result) {
            return base.Channel.Endget_Count(result);
        }
        
        private System.IAsyncResult OnBeginget_Count(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.Beginget_Count(callback, asyncState);
        }
        
        private object[] OnEndget_Count(System.IAsyncResult result) {
            int retVal = this.Endget_Count(result);
            return new object[] {
                    retVal};
        }
        
        private void Onget_CountCompleted(object state) {
            if ((this.get_CountCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.get_CountCompleted(this, new get_CountCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void get_CountAsync() {
            this.get_CountAsync(null);
        }
        
        public void get_CountAsync(object userState) {
            if ((this.onBeginget_CountDelegate == null)) {
                this.onBeginget_CountDelegate = new BeginOperationDelegate(this.OnBeginget_Count);
            }
            if ((this.onEndget_CountDelegate == null)) {
                this.onEndget_CountDelegate = new EndOperationDelegate(this.OnEndget_Count);
            }
            if ((this.onget_CountCompletedDelegate == null)) {
                this.onget_CountCompletedDelegate = new System.Threading.SendOrPostCallback(this.Onget_CountCompleted);
            }
            base.InvokeAsync(this.onBeginget_CountDelegate, null, this.onEndget_CountDelegate, this.onget_CountCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Axel.Database.remote.SearchResponse Axel.Database.remote.ServiceSoap.Search(Axel.Database.remote.SearchRequest request) {
            return base.Channel.Search(request);
        }
        
        public Axel.Database.remote.ArrayOfString[] Search(Axel.Database.remote.ArrayOfString keys) {
            Axel.Database.remote.SearchRequest inValue = new Axel.Database.remote.SearchRequest();
            inValue.Body = new Axel.Database.remote.SearchRequestBody();
            inValue.Body.keys = keys;
            Axel.Database.remote.SearchResponse retVal = ((Axel.Database.remote.ServiceSoap)(this)).Search(inValue);
            return retVal.Body.SearchResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Axel.Database.remote.ServiceSoap.BeginSearch(Axel.Database.remote.SearchRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSearch(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginSearch(Axel.Database.remote.ArrayOfString keys, System.AsyncCallback callback, object asyncState) {
            Axel.Database.remote.SearchRequest inValue = new Axel.Database.remote.SearchRequest();
            inValue.Body = new Axel.Database.remote.SearchRequestBody();
            inValue.Body.keys = keys;
            return ((Axel.Database.remote.ServiceSoap)(this)).BeginSearch(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Axel.Database.remote.SearchResponse Axel.Database.remote.ServiceSoap.EndSearch(System.IAsyncResult result) {
            return base.Channel.EndSearch(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public Axel.Database.remote.ArrayOfString[] EndSearch(System.IAsyncResult result) {
            Axel.Database.remote.SearchResponse retVal = ((Axel.Database.remote.ServiceSoap)(this)).EndSearch(result);
            return retVal.Body.SearchResult;
        }
        
        private System.IAsyncResult OnBeginSearch(object[] inValues, System.AsyncCallback callback, object asyncState) {
            Axel.Database.remote.ArrayOfString keys = ((Axel.Database.remote.ArrayOfString)(inValues[0]));
            return this.BeginSearch(keys, callback, asyncState);
        }
        
        private object[] OnEndSearch(System.IAsyncResult result) {
            Axel.Database.remote.ArrayOfString[] retVal = this.EndSearch(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSearchCompleted(object state) {
            if ((this.SearchCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SearchCompleted(this, new SearchCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SearchAsync(Axel.Database.remote.ArrayOfString keys) {
            this.SearchAsync(keys, null);
        }
        
        public void SearchAsync(Axel.Database.remote.ArrayOfString keys, object userState) {
            if ((this.onBeginSearchDelegate == null)) {
                this.onBeginSearchDelegate = new BeginOperationDelegate(this.OnBeginSearch);
            }
            if ((this.onEndSearchDelegate == null)) {
                this.onEndSearchDelegate = new EndOperationDelegate(this.OnEndSearch);
            }
            if ((this.onSearchCompletedDelegate == null)) {
                this.onSearchCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSearchCompleted);
            }
            base.InvokeAsync(this.onBeginSearchDelegate, new object[] {
                        keys}, this.onEndSearchDelegate, this.onSearchCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Axel.Database.remote.EnterResponse Axel.Database.remote.ServiceSoap.Enter(Axel.Database.remote.EnterRequest request) {
            return base.Channel.Enter(request);
        }
        
        public bool Enter(Axel.Database.remote.ArrayOfString tuple) {
            Axel.Database.remote.EnterRequest inValue = new Axel.Database.remote.EnterRequest();
            inValue.Body = new Axel.Database.remote.EnterRequestBody();
            inValue.Body.tuple = tuple;
            Axel.Database.remote.EnterResponse retVal = ((Axel.Database.remote.ServiceSoap)(this)).Enter(inValue);
            return retVal.Body.EnterResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Axel.Database.remote.ServiceSoap.BeginEnter(Axel.Database.remote.EnterRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginEnter(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginEnter(Axel.Database.remote.ArrayOfString tuple, System.AsyncCallback callback, object asyncState) {
            Axel.Database.remote.EnterRequest inValue = new Axel.Database.remote.EnterRequest();
            inValue.Body = new Axel.Database.remote.EnterRequestBody();
            inValue.Body.tuple = tuple;
            return ((Axel.Database.remote.ServiceSoap)(this)).BeginEnter(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Axel.Database.remote.EnterResponse Axel.Database.remote.ServiceSoap.EndEnter(System.IAsyncResult result) {
            return base.Channel.EndEnter(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool EndEnter(System.IAsyncResult result) {
            Axel.Database.remote.EnterResponse retVal = ((Axel.Database.remote.ServiceSoap)(this)).EndEnter(result);
            return retVal.Body.EnterResult;
        }
        
        private System.IAsyncResult OnBeginEnter(object[] inValues, System.AsyncCallback callback, object asyncState) {
            Axel.Database.remote.ArrayOfString tuple = ((Axel.Database.remote.ArrayOfString)(inValues[0]));
            return this.BeginEnter(tuple, callback, asyncState);
        }
        
        private object[] OnEndEnter(System.IAsyncResult result) {
            bool retVal = this.EndEnter(result);
            return new object[] {
                    retVal};
        }
        
        private void OnEnterCompleted(object state) {
            if ((this.EnterCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.EnterCompleted(this, new EnterCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void EnterAsync(Axel.Database.remote.ArrayOfString tuple) {
            this.EnterAsync(tuple, null);
        }
        
        public void EnterAsync(Axel.Database.remote.ArrayOfString tuple, object userState) {
            if ((this.onBeginEnterDelegate == null)) {
                this.onBeginEnterDelegate = new BeginOperationDelegate(this.OnBeginEnter);
            }
            if ((this.onEndEnterDelegate == null)) {
                this.onEndEnterDelegate = new EndOperationDelegate(this.OnEndEnter);
            }
            if ((this.onEnterCompletedDelegate == null)) {
                this.onEnterCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnEnterCompleted);
            }
            base.InvokeAsync(this.onBeginEnterDelegate, new object[] {
                        tuple}, this.onEndEnterDelegate, this.onEnterCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Axel.Database.remote.RemoveResponse Axel.Database.remote.ServiceSoap.Remove(Axel.Database.remote.RemoveRequest request) {
            return base.Channel.Remove(request);
        }
        
        public bool Remove(Axel.Database.remote.ArrayOfString keys) {
            Axel.Database.remote.RemoveRequest inValue = new Axel.Database.remote.RemoveRequest();
            inValue.Body = new Axel.Database.remote.RemoveRequestBody();
            inValue.Body.keys = keys;
            Axel.Database.remote.RemoveResponse retVal = ((Axel.Database.remote.ServiceSoap)(this)).Remove(inValue);
            return retVal.Body.RemoveResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Axel.Database.remote.ServiceSoap.BeginRemove(Axel.Database.remote.RemoveRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRemove(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginRemove(Axel.Database.remote.ArrayOfString keys, System.AsyncCallback callback, object asyncState) {
            Axel.Database.remote.RemoveRequest inValue = new Axel.Database.remote.RemoveRequest();
            inValue.Body = new Axel.Database.remote.RemoveRequestBody();
            inValue.Body.keys = keys;
            return ((Axel.Database.remote.ServiceSoap)(this)).BeginRemove(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Axel.Database.remote.RemoveResponse Axel.Database.remote.ServiceSoap.EndRemove(System.IAsyncResult result) {
            return base.Channel.EndRemove(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool EndRemove(System.IAsyncResult result) {
            Axel.Database.remote.RemoveResponse retVal = ((Axel.Database.remote.ServiceSoap)(this)).EndRemove(result);
            return retVal.Body.RemoveResult;
        }
        
        private System.IAsyncResult OnBeginRemove(object[] inValues, System.AsyncCallback callback, object asyncState) {
            Axel.Database.remote.ArrayOfString keys = ((Axel.Database.remote.ArrayOfString)(inValues[0]));
            return this.BeginRemove(keys, callback, asyncState);
        }
        
        private object[] OnEndRemove(System.IAsyncResult result) {
            bool retVal = this.EndRemove(result);
            return new object[] {
                    retVal};
        }
        
        private void OnRemoveCompleted(object state) {
            if ((this.RemoveCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RemoveCompleted(this, new RemoveCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RemoveAsync(Axel.Database.remote.ArrayOfString keys) {
            this.RemoveAsync(keys, null);
        }
        
        public void RemoveAsync(Axel.Database.remote.ArrayOfString keys, object userState) {
            if ((this.onBeginRemoveDelegate == null)) {
                this.onBeginRemoveDelegate = new BeginOperationDelegate(this.OnBeginRemove);
            }
            if ((this.onEndRemoveDelegate == null)) {
                this.onEndRemoveDelegate = new EndOperationDelegate(this.OnEndRemove);
            }
            if ((this.onRemoveCompletedDelegate == null)) {
                this.onRemoveCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRemoveCompleted);
            }
            base.InvokeAsync(this.onBeginRemoveDelegate, new object[] {
                        keys}, this.onEndRemoveDelegate, this.onRemoveCompletedDelegate, userState);
        }
    }
}
