//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace app2.dbservice {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="dbservice.DBServiceSoap")]
    public interface DBServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/get_Count", ReplyAction="*")]
        int get_Count();
        
        // CODEGEN: Generating message contract since element name keys from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Search", ReplyAction="*")]
        app2.dbservice.SearchResponse Search(app2.dbservice.SearchRequest request);
        
        // CODEGEN: Generating message contract since element name tuple from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Enter", ReplyAction="*")]
        app2.dbservice.EnterResponse Enter(app2.dbservice.EnterRequest request);
        
        // CODEGEN: Generating message contract since element name keys from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Remove", ReplyAction="*")]
        app2.dbservice.RemoveResponse Remove(app2.dbservice.RemoveRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Search", Namespace="http://tempuri.org/", Order=0)]
        public app2.dbservice.SearchRequestBody Body;
        
        public SearchRequest() {
        }
        
        public SearchRequest(app2.dbservice.SearchRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public app2.dbservice.ArrayOfString keys;
        
        public SearchRequestBody() {
        }
        
        public SearchRequestBody(app2.dbservice.ArrayOfString keys) {
            this.keys = keys;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchResponse", Namespace="http://tempuri.org/", Order=0)]
        public app2.dbservice.SearchResponseBody Body;
        
        public SearchResponse() {
        }
        
        public SearchResponse(app2.dbservice.SearchResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public app2.dbservice.ArrayOfString[] SearchResult;
        
        public SearchResponseBody() {
        }
        
        public SearchResponseBody(app2.dbservice.ArrayOfString[] SearchResult) {
            this.SearchResult = SearchResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Enter", Namespace="http://tempuri.org/", Order=0)]
        public app2.dbservice.EnterRequestBody Body;
        
        public EnterRequest() {
        }
        
        public EnterRequest(app2.dbservice.EnterRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EnterRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public app2.dbservice.ArrayOfString tuple;
        
        public EnterRequestBody() {
        }
        
        public EnterRequestBody(app2.dbservice.ArrayOfString tuple) {
            this.tuple = tuple;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnterResponse", Namespace="http://tempuri.org/", Order=0)]
        public app2.dbservice.EnterResponseBody Body;
        
        public EnterResponse() {
        }
        
        public EnterResponse(app2.dbservice.EnterResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EnterResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool EnterResult;
        
        public EnterResponseBody() {
        }
        
        public EnterResponseBody(bool EnterResult) {
            this.EnterResult = EnterResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Remove", Namespace="http://tempuri.org/", Order=0)]
        public app2.dbservice.RemoveRequestBody Body;
        
        public RemoveRequest() {
        }
        
        public RemoveRequest(app2.dbservice.RemoveRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RemoveRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public app2.dbservice.ArrayOfString keys;
        
        public RemoveRequestBody() {
        }
        
        public RemoveRequestBody(app2.dbservice.ArrayOfString keys) {
            this.keys = keys;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemoveResponse", Namespace="http://tempuri.org/", Order=0)]
        public app2.dbservice.RemoveResponseBody Body;
        
        public RemoveResponse() {
        }
        
        public RemoveResponse(app2.dbservice.RemoveResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RemoveResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool RemoveResult;
        
        public RemoveResponseBody() {
        }
        
        public RemoveResponseBody(bool RemoveResult) {
            this.RemoveResult = RemoveResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface DBServiceSoapChannel : app2.dbservice.DBServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class DBServiceSoapClient : System.ServiceModel.ClientBase<app2.dbservice.DBServiceSoap>, app2.dbservice.DBServiceSoap {
        
        public DBServiceSoapClient() {
        }
        
        public DBServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DBServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DBServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DBServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int get_Count() {
            return base.Channel.get_Count();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        app2.dbservice.SearchResponse app2.dbservice.DBServiceSoap.Search(app2.dbservice.SearchRequest request) {
            return base.Channel.Search(request);
        }
        
        public app2.dbservice.ArrayOfString[] Search(app2.dbservice.ArrayOfString keys) {
            app2.dbservice.SearchRequest inValue = new app2.dbservice.SearchRequest();
            inValue.Body = new app2.dbservice.SearchRequestBody();
            inValue.Body.keys = keys;
            app2.dbservice.SearchResponse retVal = ((app2.dbservice.DBServiceSoap)(this)).Search(inValue);
            return retVal.Body.SearchResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        app2.dbservice.EnterResponse app2.dbservice.DBServiceSoap.Enter(app2.dbservice.EnterRequest request) {
            return base.Channel.Enter(request);
        }
        
        public bool Enter(app2.dbservice.ArrayOfString tuple) {
            app2.dbservice.EnterRequest inValue = new app2.dbservice.EnterRequest();
            inValue.Body = new app2.dbservice.EnterRequestBody();
            inValue.Body.tuple = tuple;
            app2.dbservice.EnterResponse retVal = ((app2.dbservice.DBServiceSoap)(this)).Enter(inValue);
            return retVal.Body.EnterResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        app2.dbservice.RemoveResponse app2.dbservice.DBServiceSoap.Remove(app2.dbservice.RemoveRequest request) {
            return base.Channel.Remove(request);
        }
        
        public bool Remove(app2.dbservice.ArrayOfString keys) {
            app2.dbservice.RemoveRequest inValue = new app2.dbservice.RemoveRequest();
            inValue.Body = new app2.dbservice.RemoveRequestBody();
            inValue.Body.keys = keys;
            app2.dbservice.RemoveResponse retVal = ((app2.dbservice.DBServiceSoap)(this)).Remove(inValue);
            return retVal.Body.RemoveResult;
        }
    }
}
